# Generated by Django 5.1.9 on 2025-05-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='proving_key_file',
            field=models.FileField(blank=True, null=True, upload_to='zokrates/keys/'),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='verification_key_file',
            field=models.FileField(blank=True, null=True, upload_to='zokrates/keys/'),
        ),
    ]
