# Generated by Django 5.1.9 on 2025-05-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0002_identityprovider_proving_key_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprovider',
            name='hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='proving_key_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='verification_key_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
