# Generated by Django 5.1.9 on 2025-05-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0003_alter_identityprovider_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='out_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
