# Generated by Django 4.2.19 on 2025-02-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identityProviderApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityprovider",
            name="redirection_url",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="identityprovider",
            name="uid",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
