# Generated by Django 4.2.19 on 2025-02-18 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("identityProviderApp", "0002_identityprovider_redirection_url_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IdentityProvider",
            new_name="RelyingParty",
        ),
    ]
