# Generated by Django 4.2.19 on 2025-02-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identityProviderApp", "0003_rename_identityprovider_relyingparty")
    ]

    operations = [
        migrations.CreateModel(
            name="KeyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Key"),
                ),
                ("value", models.TextField(unique=True, verbose_name="Value")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
