# Generated by Django 4.2.19 on 2025-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("identityProviderApp", "0004_keyvalue")]

    operations = [
        migrations.AlterField(
            model_name="keyvalue",
            name="value",
            field=models.BinaryField(unique=True, verbose_name="Value"),
        )
    ]
