# Generated by Django 4.2.19 on 2025-02-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("identityProviderApp", "0005_alter_keyvalue_value")]

    operations = [
        migrations.AlterField(
            model_name="keyvalue",
            name="value",
            field=models.TextField(unique=True, verbose_name="Value"),
        )
    ]
