# Generated by Django 4.2.19 on 2025-02-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("identityProviderApp", "0006_alter_keyvalue_value")]

    operations = [
        migrations.AlterField(
            model_name="relyingparty",
            name="uid",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
